### ISSUE TITLE
Pool.openPoolLedger hang the DroidLibIndy

### ISSUE THREAD

**Issue by zakaio** [AxelNennker/DroidLibIndy#3]
Hi Alex,
Trying to get deeper into libindy with Android client. I've successfully run your DroidLibIndy app, got the wallet created and opened. But when I'm trying to create and open the pool :

String poolName = PoolUtils.createPoolLedgerConfig();
PoolJSONParameters.OpenPoolLedgerJSONParameter config2 = new PoolJSONParameters.OpenPoolLedgerJSONParameter(null, null);
**Pool pool = Pool.openPoolLedger(poolName, config2.toJson()).get();**

the application gets hunged for few minutes and then I'm getting TimeoutException.
Could you please point me in a possible direction to dig?
My Phone: Pixel 2xl ARM64, Android version: 9

019-06-15 05:37:14.817 17312-17312/com.zaka.wallet W/System.err: java.util.concurrent.ExecutionException: org.hyperledger.indy.sdk.ledger.TimeoutException: Timeout

**Comment by zakaio** [comment]
My fault - Pool was down...

**Comment by AxelNennker** [comment]
Thanks, for trying out DroidLibIndy. If you have something that is useful for others please contribute.
Even small things like tool or dependency updates.
Or documentation when you stumbled over something that could be avoided if the README.md were clearer...
